# Generated by Django 4.2.5 on 2023-12-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('tekshirilmoqda', 'Tekshirilmoqda'), ('tekshirildi', 'Tekshirildi'), ('rad etildi', 'Rad etildi'), ("ma'lumot topilmadi", "Ma'lumot topilmadi")], default='yangi', max_length=20, null=True)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.tuman')),
            ],
        ),
    ]
