# Generated by Django 4.2.5 on 2023-12-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('tekshirilmoqda', 'Tekshirilmoqda'), ('tekshirildi', 'Tekshirildi'), ('rad etildi', 'Rad etildi'), ("ma'lumot topilmadi", "Ma'lumot topilmadi")], default='yangi', max_length=20, null=True),
        ),
    ]
